# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Anjar Febrianto
email: befrajna@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Anjar Febrianto, Husband, Father and Web developer based in Jakarta, Indonesia. Welcome to my site, you can read my journal here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://anjarweb.xyz" # the base hostname & protocol for your site
twitter_username: befrajna
github_username:  befrajna
fb_username : befrajna
instagram_username : befrajna
linkedin_url : https://id.linkedin.com/in/befrajna
gplus_url : https://plus.google.com/u/0/+AnjarFebrianto
youtube_channel : https://www.youtube.com/channel/UCuR_Pef577Jm4RpoBbyON3A
permalink: journal/:year/:month/:day/:hour:minute:second-:title.html
# Build settings
markdown: kramdown
gem:
    - jekyll-sitemap
